version: "3.7"

services:
  gns-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ./proxy.py
        target: /opt/app/proxy.py